apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongo-express
    # namespace: mongo-project
    labels: 
      app: mongo-express
spec:
    replicas: 1
    selector:
      matchLabels:
        app: mongo-express
    template:
      metadata:
        labels: 
          app: mongo-express
      spec:
        containers: 
        - name: mongo-express
          image: mongo-express
          ports:
          - containerPort: 8081
          env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom: # takes reference from mongo-secret.yml
              secretKeyRef:
                name: mongo-secret
                key: mongo-username
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom: # takes reference from mongo-secret.yml
              secretKeyRef:
                name: mongo-secret
                key: mongo-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom: # takes reference from mongodb-configmap.yaml
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url

---
apiVersion: v1
kind: Service
metadata:
    name: mongo-express-service
spec:
    selector:
      app: mongo-express
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 8081
        targetPort: 8081
        nodePort: 30000 # node Port must be between 30000 - 32767
