apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: dXNlcm5hbWU= #dummy username and encoded with unix based64, echo -n username | base64
  password: cGFzc3dvcmQ=