apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-username: dXNlcm5hbWU= #dummy username and encoded with unix based64, echo -n username | base64
  mongo-password: cGFzc3dvcmQ=